services:
  api-gateway:
    build: ./restaurant-backend/api-gateway
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - PORT=5000
      - MENU_SERVICE_URL=http://menu-service:5001
      - ORDER_SERVICE_URL=http://order-service:5002
      - RESERVATION_SERVICE_URL=http://reservation-service:5003
      - CONTACT_SERVICE_URL=http://contact-service:5004
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  menu-service:
    build: ./restaurant-backend/menu-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  order-service:
    build: ./restaurant-backend/order-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5002/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  reservation-service:
    build: ./restaurant-backend/reservation-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5003/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  contact-service:
    build: ./restaurant-backend/contact-service
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5004/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: ./restaurant-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:5000}
    networks:
      - restaurant-network
    depends_on:
      - api-gateway

networks:
  restaurant-network:
    driver: bridge
